// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_hello
#define IOD_SYMBOL_hello
    iod_define_symbol(hello)
#endif

#ifndef IOD_SYMBOL_message
#define IOD_SYMBOL_message
    iod_define_symbol(message)
#endif

